version: '3.8'

services:
  rag-chatbot:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./chroma_db:/app/chroma_db
    restart: unless-stopped
    
  # Optional: Add Redis for session management in production
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped